# Generated by Django 4.0.4 on 2022-11-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='click_current',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='url',
            name='click_limit',
            field=models.IntegerField(default=100, max_length=10),
            preserve_default=False,
        ),
    ]
