# Generated by Django 4.0.4 on 2022-11-10 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_url_click_current_url_click_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='click_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='click_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='expiration_time',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('referer', models.CharField(max_length=250)),
                ('ip', models.GenericIPAddressField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.url')),
            ],
        ),
    ]
