# Generated by Django 4.0.4 on 2022-11-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_rename_long_url_long_url_rename_short_url_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='redirect_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
