# Generated by Django 4.0.4 on 2022-11-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_click_redirect_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='redirect_time',
            field=models.FloatField(null=True),
        ),
    ]
