# Generated by Django 4.0.4 on 2022-11-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_click_redirect_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='click_current',
        ),
    ]
