# Generated by Django 4.0.4 on 2022-11-11 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_url_click_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
