# Generated by Django 4.0.4 on 2022-11-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_click_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='click_limit',
            field=models.PositiveIntegerField(),
        ),
    ]
