# Generated by Django 4.0.4 on 2022-11-14 13:31

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_url_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='expiration_time',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 11, 14, 13, 31, 27, 178779, tzinfo=utc))]),
        ),
    ]
